version: '3.8'

services:
    api:
        build: .
        restart: always
        environment:
            DATABASE_URL: ${DATABASE_URL}
            JWT_SECRET: ${JWT_SECRET}
            API_PORT: ${API_PORT}
        ports:
            - ${API_PORT}:${API_PORT}

    database:
        image: postgres:15.2-alpine3.17
        restart: always
        environment:
            POSTGRES_DB: ${DATABASE_DB}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - database_data:/var/lib/postgresql/data

volumes:
    database_data:
