name: Build and publish image

on:
    workflow_call:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v3

            - uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - run: |
                  docker build . --tag ghcr.io/sirius-pro-tests/backend:latest
                  docker push ghcr.io/sirius-pro-tests/backend:latest
